server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: true
    evictionIntervalTimerInMs: 4000
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: 123456