server:
  port: 8763

spring:
  application:
    name: service-hi
  cloud:
    consul:
      host: 192.168.19.136
      port: 8500
      discovery:
        healthCheckPath: /hi
        healthCheckInterval: 15s
        instance-id: consul-miya